import React, { createContext, useContext, useState } from 'react'

// Traductions
const translations = {
  fr: {
    // Navigation
    home: 'Accueil',
    about: 'À propos',
    industries: 'Industries',
    services: 'Services',
    career: 'Carrière',
    contact: 'Contact',
    
    // Page d'accueil
    heroTitle: 'AfriBuilDigit Group',
    heroSubtitle1: 'Une vision stimulante.',
    heroSubtitle2: 'Une valeur ajoutée.',
    heroSubtitle: 'Votre partenaire de confiance en services informatiques',
    heroDescription: 'Jeune et dynamique entreprise spécialisée en science des données, ingénierie des données, analyse de données et développement logiciel.',
    getStarted: 'Commencer',
    learnMore: 'En savoir plus',
    ourServices: 'Nos Services',
    discoverServices: 'Découvrez notre gamme complète de services informatiques',
    learnMoreLink: 'En savoir plus',
    whyChooseUs: 'Pourquoi Nous Choisir',
    whatMakesUsDifferent: 'Découvrez ce qui nous distingue de la concurrence',
    readyToTransform: 'Prêt à Transformer Votre Entreprise ?',
    contactToday: 'Vous avez d\'autres questions, besoin d\'informations ou souhaitez être rappelé? Laissez-nous un message - Nous serons ravis de vous aider.',
    discoverOurServices: 'Découvrir nos services',
    technologiesTools: 'Technologies & Outils',
    modernTechnologies: 'Nous utilisons les technologies les plus modernes pour vos projets',
    dataScienceML: 'Data Science & ML',
    dataEngineering: 'Data Engineering',
    development: 'Développement',
    
    // Features de la page d'accueil
    experiencedTeam: 'Équipe Expérimentée',
    experiencedTeamDesc: 'Nos fondateurs cumulent de nombreuses années d\'expérience dans la mise en œuvre de solutions basées sur les données.',
    customSolutions: 'Solutions Sur Mesure',
    customSolutionsDesc: 'Nous allions expertise technique et compréhension approfondie des processus métier.',
    technicalExcellence: 'Excellence Technique',
    technicalExcellenceDesc: 'Nous maintenons les plus hauts standards de qualité dans tous nos projets.',
    continuousInnovation: 'Innovation Continue',
    continuousInnovationDesc: 'Nous restons à la pointe des dernières technologies et méthodologies.',
    
    // Statistiques
    projectsCompleted: 'Projets Réalisés',
    satisfiedClients: 'Clients Satisfaits',
    yearsExperience: 'Années d\'Expérience',
    successRate: 'Taux de Réussite',
    
    // Services
    softwareDevelopment: 'Software Engineering',
    digitale: 'Digitalisation',
    consulting: 'KI Consulting et Implementation',
    cloudsolutions: 'Cloud Solutions & Services',
    dataAnalytics: 'Analyses et Données',
    security: 'Cyber-Sécurité',
    servicesTitle: 'Nos Services',
    servicesSubtitle: 'Grâce à notre expertise technique approfondie, des outils et des méthodes modernes, nous développons des solutions avancées et sécurisées, de manière continue et efficace. Nous vous accompagnons dans la construction de votre avenir. De l\'idée à la mise en œuvre. Découvrez notre gamme complète de services informatiques spécialisés',
    whatWeOffer: 'Ce que nous offrons :',
    readyToStart: 'Prêt à commencer votre projet ?',
    contactForQuote: 'Contactez-nous pour discuter de vos besoins et obtenir un devis personnalisé',
    
    // Nouveaux services
    softwareEngineering: 'Développement logiciel',
    dataAnalyticsServices: 'Analyses de données',
    aiMlDataScience: 'AI, ML, and Data Science',
    cloudDataEngineering: 'Ingénieur de données cloud',
    cloudServices: 'Cloud',
    cybersecurity: 'Cybersecurity',
    embeddedSoftwareIoT: 'Software embarquées et IoT',
    intelligentPlatformsRPA: 'Plateformes intelligentes et RPA',
    digitalTransformation: 'Transformation digitale',

    // Descriptions des services
    consultingDesc: 'Des solutions d\'IA conçues pour votre entreprise. Boostez votre efficacité et votre croissance avec AfriBuilDigit.',
    cloudsolutionsDesc: 'Accélérez votre transition vers le cloud avec AfriBuilDigit. Bénéficiez d\'une rentabilité plus rapide.',
    dataAnalyticsDesc: 'Libérez la puissance des données avec AfriBuilDigit. Des informations basées sur l\'IA, des plateformes modernisées et des solutions prêtes pour l\'avenir.',
    softwareDevelopmentDesc: 'Nous développons des applications robustes et innovantes adaptées à vos besoins spécifiques.',
    digitaleDesc: 'Nous développons des applications robustes et innovantes adaptées à vos besoins spécifiques.',
    securityDesc: 'Nous développons des applications robustes et innovantes adaptées à vos besoins spécifiques.',
    
    // Descriptions des nouveaux services
    softwareEngineeringDesc: 'Que vous ayez besoin de valider une idée, de créer une solution sur mesure, de moderniser votre système, d\'optimiser vos processus existants ou d\'exploiter de nouvelles technologies, AfriBuilDigit est là pour vous. Nous allions une connaissance approfondie du domaine, une expertise des technologies de pointe et une attention particulière à vos besoins pour vous fournir des solutions et services technologiques performants. Outre les solutions cloud, l\'analyse de données, l\'IA, l\'IoT et la conception UX, nous proposons une large gamme de services d\'ingénierie logicielle.',
    dataAnalyticsServicesDesc: 'Optimisez vos opérations, réduisez les risques et transformez vos données en revenus avec un partenaire de confiance à vos côtés. Avec des ingénieurs data expérimentés et une expérience reconnue en analyse de données, AfriBuilDigit répond à tous vos besoins métier, de la conception d\'une stratégie gagnante à la mise en place d\'une gouvernance des données efficace, en passant par l\'ingénierie Big Data et la création de plateformes de données complexes.',
    aiMlDataScienceDesc: 'Grâce à l\'expertise de AfriBuilDigit en IA, Machine Learning et Data Science, vous pouvez atteindre tous vos objectifs : automatisation des opérations, gain de productivité, prise de décisions éclairées basées sur les données et augmentation des profits. Nos experts vous aident à extraire des insights de volumes massifs de données structurées et non structurées, à mettre en œuvre des solutions de vision par ordinateur, à établir des modèles de deep learning, et bien plus encore.',
    cloudDataEngineeringDesc: 'Disposer des bonnes données, au bon moment et au bon format, constitue un avantage concurrentiel pour les entreprises. Cependant, gérer la complexité et les volumes de données peut s\'avérer complexe pour les entreprises : collecter, traiter et analyser. Chez AfriBuilDigit, nos services d\'ingénierie des données cloud vous aident à créer l\'infrastructure de données idéale pour collecter, traiter et accéder facilement à vos données d\'entreprise afin d\'obtenir des informations exploitables partout, à tout moment et sur n\'importe quel appareil.',
    cloudServicesDesc: 'AfriBuilDigit a pour but d\'aidé les organisations à concevoir, mettre en œuvre et perfectionner continuellement leur parcours cloud. Nous proposons une gamme complète de services de développement cloud : de la stratégie et de l\'adoption du cloud au DevOps, en passant par l\'optimisation CI/CD, et bien plus encore. Avec nos ingénieurs cloud et des dizaines de projets réalisés, nous pouvons aider votre entreprise à tirer de nombreux avantages à long terme de vos initiatives cloud : agilité, réduction des coûts, délais de commercialisation plus courts, meilleure expérience client, et bien plus encore.',
    cybersecurityDesc: 'Une cybersécurité robuste n\'est pas une simple option, c\'est une nécessité absolue. La complexité et la fréquence croissantes des cybermenaces exigent des mesures de sécurité proactives et complètes pour protéger les actifs les plus précieux de votre entreprise. AfriBuilDigit propose des services de conseil en cybersécurité experts, conçus pour protéger votre organisation des menaces potentielles et garantir l\'intégrité, la confidentialité et la disponibilité de vos données.',
    embeddedSoftwareIoTDesc: 'En tant que partenaire de développement de logiciels embarqués et d\'IoT sur l\'ensemble du cycle de vie, AfriBuilDigit vous accompagne dans tous les aspects de votre projet IoT ou embarqué, de la validation de votre idée et de la création d\'un prototype à la conception d\'une architecture cloud évolutive et à l\'exploitation optimale de l\'analyse prédictive. Notre approche unique garantit un accompagnement complet à chaque étape et optimise le cycle de développement, optimisant ainsi les coûts et les délais.',
    intelligentPlatformsRPADesc: 'Fort de plus de vingt ans d\'expérience en développement de logiciels sur mesure et de plus de quinze ans en conseil aux entreprises, AfriBuilDigit offre une expertise approfondie de nombreuses plateformes numériques et outils RPA tels que SAP, OpenText, Salesforce, Automation Anywhere, UIPath, entre autres. Nos consultants certifiés ont collaboré avec des dizaines d\'entreprises du Fortune 500 et des entreprises leaders dans les secteurs de la finance, des télécommunications, de l\'industrie manufacturière, de la chaîne d\'approvisionnement, de la distribution et d\'autres secteurs, les aidant à optimiser la valeur de leurs applications d\'entreprise.',
    digitalTransformationDesc: 'La transformation numérique, c\'est un peu comme déclencher une avalanche : tout commence par une bonne idée, et dès sa mise en œuvre, toute l\'entreprise change radicalement. Un conseil professionnel aide votre équipe à trouver de nouvelles façons d\'établir des processus efficaces et de mettre en œuvre des modèles économiques numériques.',
    
    // Sous-services
    softwareEngineeringServices: 'Software Engineering Services',
    customSolutionDevelopment: 'Custom Solution Development',
    applicationModernisation: 'Application Modernisation',
    softwareQATesting: 'Software QA & Testing',
    technologyConsulting: 'Technology Consulting',
    softwareArchitectureConsulting: 'Software Architecture Consulting',
    techDueDiligence: 'Tech Due Diligence',
    digitalTransformationServices: 'Digital Transformation',
    productDiscovery: 'Product Discovery',
    
    dataAnalyticsServicesList: 'Data Analytics services',
    dataAnalyticsStrategy: 'Data Analytics Strategy',
    bigData: 'Big Data',
    dataGovernance: 'Data Governance',
    dataWarehouseConsulting: 'Data Warehouse Consulting',
    dataLakeConsulting: 'Data Lake Consulting',
    businessIntelligence: 'Business Intelligence',
    
    aiMlDataScienceServices: 'AI, ML et Data Science',
    dataScienceServices: 'Data Science',
    artificialIntelligenceML: 'Artificial Intelligence and Machine Learning Development',
    mlOps: 'MLOps',
    generativeAIConsulting: 'Generative AI Consulting',
    aiConsulting: 'AI Consulting',
    computerVisionDevelopment: 'Computer Vision Development',
    
    cloudDataServices: 'Cloud Data Services',
    cloudMigration: 'Cloud Migration',
    cloudArchitectureStrategies: 'Cloud Architecture et Strategies',
    devOpsAutomation: 'DevOps et Automatisation',
    cloudInfrastructureManagement: 'Cloud Infrastructure Management',
    cloudDataIntegrationETL: 'Cloud Data Integration et ETL',
    
    cloudSolutions: 'Cloud Solutions',
    cloudNativeServices: 'Cloud‑native Services',
    devOps: 'DevOps',
    awsConsulting: 'AWS Consulting',
    awsMigration: 'AWS Migration',
    awsOpenSearchService: 'AWS OpenSearch Service',
    awsWellArchitectedReview: 'AWS Well‑Architected Review',
    cloudInfrastructureManagementServices: 'Cloud Infrastructure Management',
    azureConsulting: 'Azure Consulting',
    gcpConsulting: 'GCP Consulting',
    
    cybersecurityServices: 'Cybersecurity',
    businessContinuity: 'Business Continuity',
    devSecOps: 'DevSecOps',
    penetrationTesting: 'Penetration Testing',
    strategyConsulting: 'Strategy and Consulting',
    applicationSecurity: 'Application Security',
    riskAssessment: 'Risk Assessment',
    compliance: 'Compliance',
    
    embeddedSoftwareDevelopment: 'Embedded Software Development',
    internetOfThingsDevelopment: 'Internet of Things Development',
    firmwareDevelopmentServices: 'Firmware Development Services',
    roboticsConsulting: 'Robotics Consulting',
    
    sapConsulting: 'SAP Consulting',
    sapOnAws: 'SAP on AWS',
    openTextProfessionalServices: 'OpenText Professional Services',
    salesforce: 'Salesforce',
    intelligentAutomation: 'Intelligent Automation',
    rpa: 'RPA',
    lowCodeNoCodeDevelopment: 'Low‑Code/No‑Code Development',
    mendix: 'Mendix',
    pega: 'Pega',
    uiPath: 'UIPath',
    
    digitalisationStrategies: 'Stratégies de digitalisation',
    changeManagement: 'Gestion du changement',
    cloudService: 'Cloud Service',
    financialTransformation: 'Transformation financière',
    digitalControl: 'Contrôle digital',
    
    
    // Features des services
    predictionModels: 'Modèles de prédiction avancés',
    sentimentAnalysis: 'Analyse de sentiment',
    personalizedRecommendation: 'Recommandation personnalisée',
    computerVision: 'Computer Vision',
    naturalLanguageProcessing: 'Traitement du langage naturel',
    processOptimization: 'Optimisation des processus',
    cloudNativeArchitectures: 'Architectures cloud-native',
    dataPipelines: 'Pipelines de données ETL/ELT',
    dataLakes: 'Data lakes et data warehouses',
    realTimeStreaming: 'Streaming de données en temps réel',
    dataQualityManagement: 'Gestion de la qualité des données',
    monitoringAlerting: 'Monitoring et alerting',
    interactiveDashboards: 'Tableaux de bord interactifs',
    automatedReports: 'Rapports automatisés',
    predictiveAnalysis: 'Analyse prédictive',
    customerSegmentation: 'Segmentation client',
    businessKPIs: 'KPI et métriques business',
    dataVisualization: 'Visualisation de données',
    modernWebApps: 'Applications web modernes',
    restfulAPIs: 'APIs RESTful et GraphQL',
    mobileApps: 'Applications mobiles',
    managementSystems: 'Systèmes de gestion',
    thirdPartyIntegrations: 'Intégrations tierces',
    maintenanceSupport: 'Maintenance et support',
    
    // clients
    clientsTitle: 'Nos Clients',
    clientsSubtitle: 'Les exigences informatiques de nos clients sont aussi variés que leurs entreprises et leurs secteurs d\'activité. Cependant, ils ont un point commun : ils reconnaissent que des environnements informatiques modernes et fiables constituent le fondement de modèles économiques durables et de la réussite économique.',
    
    // Solutions IT
    ourITSoftwareSolutions: 'Nos Solutions IT et Logiciels',
    advancedITForBusinessSuccess: 'IT Avancée pour Votre Succès Commercial',
    solutionsFirstParagraph: 'En tant que spécialiste hautement certifié des services informatiques, nous disposons d\'un large portefeuille de services : des services cloud les plus modernes aux infrastructures informatiques sur mesure et services gérés, en passant par les sujets de sécurité et autres services de support, tout est inclus pour une informatique d\'entreprise bien positionnée afin de répondre aux exigences croissantes de la transformation numérique.',
    solutionsSecondParagraph: 'Avec nos solutions logicielles intelligentes, nous maîtrisons les défis individuels et optimisons les processus métier complexes en étroite collaboration avec nos clients. Nous répondons précisément aux besoins spécifiques de l\'industrie de nos clients et trouvons soit la bonne solution dans notre portefeuille logiciel étendu, soit nous développons le logiciel approprié sur mesure pour votre entreprise.',
    
    // À propos
    aboutTitle: 'À propos de nous',
    aboutDescription: 'Nous sommes une jeune et dynamique entreprise de services informatiques basée à Yaoundé, au Cameroun.',
    experience: 'Expérience',
    expertise: 'Expertise',
    innovation: 'Innovation',
    ourHistory: 'Notre Histoire',
    historySubtitle: 'Découvrez le parcours qui nous a menés jusqu\'ici',
    visionFromExperience: 'Une vision née de l\'expérience',
    visionDescription: 'AfriBuilDigit Group est née de la vision de créer une entreprise de services informatiques qui allie expertise technique et compréhension approfondie des processus métier. Nos fondateurs, après avoir travaillé dans de grandes entreprises internationales, ont décidé de mettre leur expertise au service des entreprises africaines.',
    basedInYaounde: 'Basée à Yaoundé, au Cameroun, notre entreprise s\'est rapidement imposée comme un partenaire de confiance pour les organisations cherchant à transformer leurs données en avantages concurrentiels.',
    foundingYear: 'Année de création',
    founders: 'Fondateurs',
    projectsCompleted: 'Projets réalisés',
    ourValues: 'Nos Valeurs',
    valuesSubtitle: 'Les principes qui guident nos actions au quotidien',
    excellence: 'Excellence',
    excellenceDesc: 'Nous visons l\'excellence dans tout ce que nous faisons, en maintenant les plus hauts standards de qualité.',
    passion: 'Passion',
    passionDesc: 'Nous sommes passionnés par la technologie et l\'innovation, et nous transmettons cette passion à nos clients.',
    collaboration: 'Collaboration',
    collaborationDesc: 'Nous croyons en la puissance de la collaboration et travaillons en étroite relation avec nos clients.',
    innovation: 'Innovation',
    innovationDesc: 'Nous restons à la pointe des dernières technologies pour offrir des solutions innovantes.',
    ourTeam: 'Notre Équipe',
    teamSubtitle: 'Rencontrez les experts qui font d\'AfriBuilDigit Group votre partenaire de confiance',
    ceoFounder: 'CEO & Co-fondateur',
    ctoFounder: 'CTO & Co-fondateur',
    leadDataScientist: 'Lead Data Scientist',
    ctoDesc: 'Expert en Cloud data science et Ingénieure de données avec plus de 10 ans d\'expérience professionnel.',
    ceoDesc: 'Expert en Cloud data science et Ingénieure en développement logiciel spécialisée dans les architectures cloud.',
    dataScientistDesc: 'Spécialiste en machine learning et intelligence artificielle.',
    ourMission: 'Notre Mission',
    missionDescription: 'Nous aidons nos clients à prendre des décisions fondées sur les données et à mettre en œuvre efficacement des solutions numériques. Qu\'il s\'agisse d\'architectes de données modernes, d\'applications de machine learning ou de développement back-end robuste, nous sommes votre partenaire de confiance.',
    africanContext: 'Solutions adaptées au contexte africain',
    technicalExcellence: 'Excellence technique reconnue',
    measurableResults: 'Résultats mesurables et durables',
    
    // Footer
    followUs: 'Suivez-nous',
    allRightsReserved: 'Tous droits réservés',
    
    // Contact
    contactUs: 'Contactez-nous',
    name: 'Nom',
    email: 'Email',
    message: 'Message',
    send: 'Envoyer',
    contactInfo: 'Informations de contact',
    contactInfoDesc: 'N\'hésitez pas à nous contacter pour toute question. Nous serons ravis de vous accompagner et de vous conseiller personnellement. Nous prendrons le temps d\'écouter vos besoins et de vous proposer, à vous et à votre entreprise, des solutions sur mesure qui vous mèneront au succès. Veuillez utiliser notre formulaire pour nous contacter. Nous vous répondrons dans les plus brefs délais !',
    
    // Industries
    industriesTitle: 'Nos Industries',
    industriesSubtitle: 'Nous servons divers secteurs d\'activité avec des solutions adaptées',
    healthcare: 'Santé',
    finance: 'Finance',
    agritech:'Agritech',
    transport: 'Transports publics',
    retail: 'Commerce & E-Commerce',
    manufacturing: 'Manufacture',
    readyToTransformIndustry: 'Prêt à transformer votre secteur d\'activité ?',
    contactForIndustry: 'Contactez-nous pour discuter de vos besoins spécifiques et découvrir nos solutions adaptées à votre industrie',
    
    // Descriptions des industries
    healthcareDesc: 'Solutions innovantes pour améliorer les soins de santé et optimiser les processus médicaux.',
    financeDesc: 'Technologies avancées pour sécuriser les transactions et optimiser les services financiers.',
    retailDesc: 'Solutions e-commerce et analytics pour optimiser l\'expérience client et les ventes.',
    manufacturingDesc: 'IoT et analytics pour améliorer la productivité et réduire les coûts de production.',
    
    // Solutions des industries
    diseasePrediction: 'Analyse prédictive des maladies',
    patientRecords: 'Gestion des dossiers patients',
    resourceOptimization: 'Optimisation des ressources',
    fraudDetection: 'Détection de fraude',
    riskAnalysis: 'Analyse de risque',
    algorithmicTrading: 'Trading algorithmique',
    productRecommendation: 'Recommandation produits',
    behavioralAnalysis: 'Analyse comportementale',
    inventoryOptimization: 'Optimisation des stocks',
    predictiveMaintenance: 'Maintenance prédictive',
    supplyChainOptimization: 'Optimisation de la chaîne logistique',
    automatedQuality: 'Qualité automatisée',
    
    // Carrière
    careerTitle: 'Carrière',
    joinUs: 'Rejoignez-nous',
    openPositions: 'Postes ouverts',
    careerJoinTagline: "et faites partie d'une équipe passionnée par l'innovation",
    careerOpenPositionsDesc: 'Découvrez les opportunités de carrière chez AfriBuilDigit Group',
    applyNow: 'Postuler',
    benefitsTitle: 'Avantages',
    benefitsWhyJoin: 'Pourquoi rejoindre notre équipe ?',
    benefitFlexibleWork: 'Environnement de travail flexible',
    benefitContinuousTraining: 'Formation continue',
    benefitInnovativeProjects: 'Projets innovants',
    benefitDynamicTeam: 'Équipe dynamique',
    benefitCareerGrowth: 'Croissance de carrière',
    benefitCompetitiveSalary: 'Salaire compétitif',
    careerNoIdealPosition: 'Vous ne trouvez pas le poste idéal ?',
    careerSendCVPrompt: 'Envoyez-nous votre CV et nous vous contacterons pour les futures opportunités',
    careerSendCVButton: 'Envoyer votre CV',
    positionDataScientistTitle: 'Data Scientist Senior',
    positionDataScientistDept: 'Data Science',
    positionDataScientistLocation: 'Yaoundé, Cameroun',
    positionDataScientistType: 'Temps plein',
    positionDataScientistDesc: "Nous recherchons un Data Scientist expérimenté pour rejoindre notre équipe.",
    positionFullStackTitle: 'Développeur Full Stack',
    positionFullStackDept: 'Développement',
    positionFullStackLocation: 'Yaoundé, Cameroun',
    positionFullStackType: 'Temps plein',
    positionFullStackDesc: 'Développeur passionné pour créer des applications web modernes.',
    positionDataEngineerTitle: 'Data Engineer',
    positionDataEngineerDept: 'Data Engineering',
    positionDataEngineerLocation: 'Yaoundé, Cameroun',
    positionDataEngineerType: 'Temps plein',
    positionDataEngineerDesc: 'Expert en architectures de données et pipelines ETL.',
    
    // Langues
    language: 'Langue'
  },
  ////////////////////////////////////////////////////////////////////////////////////
                          /////########### langue anglaise ###########
  en: {
    // Navigation
    home: 'Home',
    about: 'About',
    industries: 'Industries',
    services: 'Services',
    career: 'Career',
    contact: 'Contact',
    
    // Home page
    heroTitle: 'AfriBuilDigit Group',
    heroSubtitle1: 'Empowering vision.',
    heroSubtitle2: 'Delivering value.',
    heroSubtitle: 'Your trusted partner in IT services',
    heroDescription: 'Young and dynamic company specialized in data science, data engineering, data analytics and software development.',
    getStarted: 'Get Started',
    learnMore: 'Learn More',
    ourServices: 'Our Services',
    discoverServices: 'Discover our complete range of specialized IT services',
    learnMoreLink: 'Learn More',
    whyChooseUs: 'Why Choose Us',
    whatMakesUsDifferent: 'Discover what sets us apart from the competition',
    readyToTransform: 'Ready to Transform Your Business?',
    contactToday: 'Do you have any further questions, need more information, or would you like us to call you back? Leave us a message - we\'re happy to help.',
    discoverOurServices: 'Discover our services',
    technologiesTools: 'Technologies & Tools',
    modernTechnologies: 'We use the most modern technologies for your projects',
    dataScienceML: 'Data Science & ML',
    dataEngineering: 'Data Engineering',
    development: 'Development',
    
    // Features of the home page
    experiencedTeam: 'Experienced Team',
    experiencedTeamDesc: 'Our founders cumulate many years of experience in implementing data-based solutions.',
    customSolutions: 'Custom Solutions',
    customSolutionsDesc: 'We bring technical expertise and deep understanding of business processes.',
    technicalExcellence: 'Technical Excellence',
    technicalExcellenceDesc: 'We maintain the highest quality standards in all our projects.',
    continuousInnovation: 'Continuous Innovation',
    continuousInnovationDesc: 'We remain at the forefront of the latest technologies and methodologies.',
    
    // Statistics
    projectsCompleted: 'Projects Completed',
    satisfiedClients: 'Satisfied Clients',
    yearsExperience: 'Years of Experience',
    successRate: 'Success Rate',
    
    // Services
    softwareDevelopment: 'Software Engineering',
    digitale: 'Digitalisation',
    consulting: 'AI Consulting and Implementation',
    cloudsolutions: 'Cloud Solutions & Services',
    dataAnalytics: 'Data and Analytics',
    security: 'Cybersecurity',
    servicesTitle: 'Our Services',
    servicesSubtitle: 'With broad technical expertise, modern tools and methods, we develop advanced and secure solutions, continuously and efficiently. We support you in building your future. From idea to implementation. Discover our complete range of specialized IT services',
    whatWeOffer: 'What we offer:',
    readyToStart: 'Ready to start your project?',
    contactForQuote: 'Contact us to discuss your needs and get a personalized quote',
    
    // New services
    softwareEngineering: 'Software Engineering',
    dataAnalyticsServices: 'Data Analytics',
    aiMlDataScience: 'AI, ML, and Data Science',
    cloudDataEngineering: 'Cloud Data Engineering',
    cloudServices: 'Cloud',
    cybersecurity: 'Cybersecurity',
    embeddedSoftwareIoT: 'Embedded Software and IoT',
    intelligentPlatformsRPA: 'Intelligent Platforms and RPA',
    digitalTransformation: 'Digital Transformation',
    
    // service descriptions
    consultingDesc: 'Ai solutions built for your business. Drive efficiency and growth with AfriBuilDigit.',
    cloudsolutionsDesc: 'Accelerate your cloud journey with AfriBuilDigit. Achieve faster time-of-value.',
    dataAnalyticsDesc: 'Unlock the power of Data with AfriBuilDigit. AI-driven insights, modernized platforms and future-ready solutions.',
    softwareDevelopmentDesc: 'We develop robust and innovative applications tailored to your specific needs.',
    digitaleDesc: 'Nous développons des applications robustes et innovantes adaptées à vos besoins spécifiques.',
    securityDesc: 'Nous développons des applications robustes et innovantes adaptées à vos besoins spécifiques.',

    // New service descriptions
    softwareEngineeringDesc: 'Whether you need to validate an idea, create a custom solution, modernize your system, optimize your existing processes, or leverage new technologies, AfriBuilDigit is here for you. We combine deep domain knowledge, cutting-edge technology expertise, and careful attention to your needs to provide you with high-performance technological solutions and services. Beyond cloud solutions, data analytics, AI, IoT, and UX design, we offer a wide range of software engineering services.',
    dataAnalyticsServicesDesc: 'Optimize your operations, reduce risks, and transform your data into revenue with a trusted partner by your side. With experienced data engineers and recognized expertise in data analytics, AfriBuilDigit meets all your business needs, from designing a winning strategy to implementing effective data governance, through Big Data engineering and creating complex data platforms.',
    aiMlDataScienceDesc: 'Thanks to AfriBuilDigit\'s expertise in AI, Machine Learning, and Data Science, you can achieve all your goals: operations automation, productivity gains, data-driven decision making, and profit increases. Our experts help you extract insights from massive volumes of structured and unstructured data, implement computer vision solutions, establish deep learning models, and much more.',
    cloudDataEngineeringDesc: 'Having the right data, at the right time and in the right format, constitutes a competitive advantage for businesses. However, managing data complexity and volumes can be complex for companies: collect, process, and analyze. At AfriBuilDigit, our cloud data engineering services help you create the ideal data infrastructure to collect, process, and easily access your business data to obtain actionable insights anywhere, anytime, and on any device.',
    cloudServicesDesc: 'AfriBuilDigit aims to help organizations design, implement, and continuously perfect their cloud journey. We offer a comprehensive range of cloud development services: from cloud strategy and adoption to DevOps, through CI/CD optimization, and much more. With our cloud engineers and dozens of completed projects, we can help your company derive many long-term benefits from your cloud initiatives: agility, cost reduction, shorter time to market, better customer experience, and much more.',
    cybersecurityDesc: 'Robust cybersecurity is not a simple option, it\'s an absolute necessity. The growing complexity and frequency of cyber threats require proactive and comprehensive security measures to protect your company\'s most valuable assets. AfriBuilDigit offers expert cybersecurity consulting services, designed to protect your organization from potential threats and ensure the integrity, confidentiality, and availability of your data.',
    embeddedSoftwareIoTDesc: 'As a full-lifecycle embedded software and IoT development partner, AfriBuilDigit accompanies you in all aspects of your IoT or embedded project, from validating your idea and creating a prototype to designing a scalable cloud architecture and optimally leveraging predictive analytics. Our unique approach ensures comprehensive support at every step and optimizes the development cycle, thus optimizing costs and timelines.',
    intelligentPlatformsRPADesc: 'With over twenty years of experience in custom software development and over fifteen years in business consulting, AfriBuilDigit offers deep expertise in many digital platforms and RPA tools such as SAP, OpenText, Salesforce, Automation Anywhere, UIPath, among others. Our certified consultants have collaborated with dozens of Fortune 500 companies and leading companies in the finance, telecommunications, manufacturing, supply chain, distribution, and other sectors, helping them optimize the value of their enterprise applications.',
    digitalTransformationDesc: 'Digital transformation is a bit like triggering an avalanche: it all starts with a good idea, and as soon as it\'s implemented, the entire company changes radically. Professional consulting helps your team find new ways to establish efficient processes and implement digital business models.',
    
    // Sub-services
    softwareEngineeringServices: 'Software Engineering Services',
    customSolutionDevelopment: 'Custom Solution Development',
    applicationModernisation: 'Application Modernisation',
    softwareQATesting: 'Software QA & Testing',
    technologyConsulting: 'Technology Consulting',
    softwareArchitectureConsulting: 'Software Architecture Consulting',
    techDueDiligence: 'Tech Due Diligence',
    digitalTransformationServices: 'Digital Transformation',
    productDiscovery: 'Product Discovery',
    
    dataAnalyticsServicesList: 'Data Analytics services',
    dataAnalyticsStrategy: 'Data Analytics Strategy',
    bigData: 'Big Data',
    dataGovernance: 'Data Governance',
    dataWarehouseConsulting: 'Data Warehouse Consulting',
    dataLakeConsulting: 'Data Lake Consulting',
    businessIntelligence: 'Business Intelligence',
    
    aiMlDataScienceServices: 'AI, ML and Data Science',
    dataScienceServices: 'Data Science',
    artificialIntelligenceML: 'Artificial Intelligence and Machine Learning Development',
    mlOps: 'MLOps',
    generativeAIConsulting: 'Generative AI Consulting',
    aiConsulting: 'AI Consulting',
    computerVisionDevelopment: 'Computer Vision Development',
    
    cloudDataServices: 'Cloud Data Services',
    cloudMigration: 'Cloud Migration',
    cloudArchitectureStrategies: 'Cloud Architecture and Strategies',
    devOpsAutomation: 'DevOps and Automation',
    cloudInfrastructureManagement: 'Cloud Infrastructure Management',
    cloudDataIntegrationETL: 'Cloud Data Integration and ETL',
    
    cloudSolutions: 'Cloud Solutions',
    cloudNativeServices: 'Cloud‑native Services',
    devOps: 'DevOps',
    awsConsulting: 'AWS Consulting',
    awsMigration: 'AWS Migration',
    awsOpenSearchService: 'AWS OpenSearch Service',
    awsWellArchitectedReview: 'AWS Well‑Architected Review',
    cloudInfrastructureManagementServices: 'Cloud Infrastructure Management',
    azureConsulting: 'Azure Consulting',
    gcpConsulting: 'GCP Consulting',
    
    cybersecurityServices: 'Cybersecurity',
    businessContinuity: 'Business Continuity',
    devSecOps: 'DevSecOps',
    penetrationTesting: 'Penetration Testing',
    strategyConsulting: 'Strategy and Consulting',
    applicationSecurity: 'Application Security',
    riskAssessment: 'Risk Assessment',
    compliance: 'Compliance',
    
    embeddedSoftwareDevelopment: 'Embedded Software Development',
    internetOfThingsDevelopment: 'Internet of Things Development',
    firmwareDevelopmentServices: 'Firmware Development Services',
    roboticsConsulting: 'Robotics Consulting',
    
    sapConsulting: 'SAP Consulting',
    sapOnAws: 'SAP on AWS',
    openTextProfessionalServices: 'OpenText Professional Services',
    salesforce: 'Salesforce',
    intelligentAutomation: 'Intelligent Automation',
    rpa: 'RPA',
    lowCodeNoCodeDevelopment: 'Low‑Code/No‑Code Development',
    mendix: 'Mendix',
    pega: 'Pega',
    uiPath: 'UIPath',
    
    digitalisationStrategies: 'Digitalisation Strategies',
    changeManagement: 'Change Management',
    cloudService: 'Cloud Service',
    financialTransformation: 'Financial Transformation',
    digitalControl: 'Digital Control',
  
    
    // Service features
    predictionModels: 'Advanced prediction models',
    sentimentAnalysis: 'Sentiment analysis',
    personalizedRecommendation: 'Personalized recommendation',
    computerVision: 'Computer Vision',
    naturalLanguageProcessing: 'Natural Language Processing',
    processOptimization: 'Process optimization',
    cloudNativeArchitectures: 'Cloud-native architectures',
    dataPipelines: 'ETL/ELT data pipelines',
    dataLakes: 'Data lakes and data warehouses',
    realTimeStreaming: 'Real-time data streaming',
    dataQualityManagement: 'Data quality management',
    monitoringAlerting: 'Monitoring and alerting',
    interactiveDashboards: 'Interactive dashboards',
    automatedReports: 'Automated reports',
    predictiveAnalysis: 'Predictive analysis',
    customerSegmentation: 'Customer segmentation',
    businessKPIs: 'Business KPIs and metrics',
    dataVisualization: 'Data visualization',
    modernWebApps: 'Modern web applications',
    restfulAPIs: 'RESTful and GraphQL APIs',
    mobileApps: 'Mobile applications',
    managementSystems: 'Management systems',
    thirdPartyIntegrations: 'Third-party integrations',
    maintenanceSupport: 'Maintenance and support',
    
    // clients
    clientsTitle: 'Our Clients',
    clientsSubtitle: 'Our customers\' IT requirements are as diverse as their companies and industries. However, they have one thing in common: they recognize that modern and reliable IT environments are the foundation of sustainable business models and economic success.',
    
    // Solutions IT
    ourITSoftwareSolutions: 'Our IT and Software Solutions',
    advancedITForBusinessSuccess: 'Advanced IT for Your Business Success',
    solutionsFirstParagraph: 'As a highly certified specialist in IT services, we have a wide portfolio of services: from the most modern cloud services to custom IT infrastructure and managed services, including security and other support topics, all is included for a well-positioned enterprise IT to meet the increasing requirements of digital transformation.',
    solutionsSecondParagraph: 'With our intelligent software solutions, we master individual challenges and optimize complex business processes in close collaboration with our clients. We precisely meet the specific needs of our clients\' industry and find either the right solution in our extended software portfolio, or we develop the appropriate custom software for your company.',
    
    // About
    aboutTitle: 'About Us',
    aboutDescription: 'We are a young and dynamic IT services company based in Yaoundé, Cameroon.',
    experience: 'Experience',
    expertise: 'Expertise',
    innovation: 'Innovation',
    ourHistory: 'Our History',
    historySubtitle: 'Discover the journey that led us here',
    visionFromExperience: 'A vision born from experience',
    visionDescription: 'AfriBuilDigit Group was born from the vision to create an IT services company that combines technical expertise and deep understanding of business processes. Our founders, after working in large international companies, decided to put their expertise to the service of African businesses.',
    basedInYaounde: 'Based in Yaoundé, Cameroon, our company quickly established itself as a trusted partner for organizations seeking to transform their data into competitive advantages.',
    foundingYear: 'Creation year',
    founders: 'Founders',
    projectsCompleted: 'Projects completed',
    ourValues: 'Our Values',
    valuesSubtitle: 'The principles that guide our daily actions',
    excellence: 'Excellence',
    excellenceDesc: 'We aim for excellence in everything we do, maintaining the highest quality standards.',
    passion: 'Passion',
    passionDesc: 'We are passionate about technology and innovation, and we pass this passion on to our clients.',
    collaboration: 'Collaboration',
    collaborationDesc: 'We believe in the power of collaboration and work closely with our clients.',
    innovation: 'Innovation',
    innovationDesc: 'We remain at the forefront of the latest technologies to offer innovative solutions.',
    ourTeam: 'Our Team',
    teamSubtitle: 'Meet the experts who make AfriBuilDigit Group your trusted partner',
    ceoFounder: 'CEO & Co-founder',
    ctoFounder: 'CTO & Co-founder',
    leadDataScientist: 'Lead Data Scientist',
    ctoDesc: 'Expert in Cloud data science and data engineering with over 10 years of professional experience.',
    ceoDesc: 'Expert in Cloud data science and Software engineering specialized in cloud architectures.',
    dataScientistDesc: 'Specialist in machine learning and artificial intelligence.',
    ourMission: 'Our Mission',
    missionDescription: 'We help our clients make data-driven decisions and effectively implement digital solutions. Whether it\'s modern data architects, machine learning applications, or robust back-end development, we are your trusted partner.',
    africanContext: 'Solutions adapted to the African context',
    technicalExcellence: 'Recognized technical excellence',
    measurableResults: 'Measurable and durable results',
    
    // Footer
    followUs: 'Follow Us',
    allRightsReserved: 'All rights reserved',
    
    // Contact
    contactUs: 'Contact Us',
    name: 'Name',
    email: 'Email',
    message: 'Message',
    send: 'Send',
    contactInfo: 'Contact Information',
    contactInfoDesc: 'Please contact us for any questions. We will be happy to accompany you and advise you personally. We will take the time to listen to your needs and offer you, to you and your company, tailored solutions that will lead you to success. Please use our form to contact us. We will respond to you in the shortest possible time!',
    
    // Industries
    industriesTitle: 'Our Industries',
    industriesSubtitle: 'We serve various business sectors with tailored solutions',
    healthcare: 'Healthcare',
    finance: 'Finance',
    agritech:'Agritech',
    transport: 'Public Transport',
    retail: 'Retail & E-Commerce',
    manufacturing: 'Manufacturing',
    readyToTransformIndustry: 'Ready to transform your industry?',
    contactForIndustry: 'Contact us to discuss your specific needs and discover our solutions adapted to your industry',
    
    // Industry descriptions
    healthcareDesc: 'Innovative solutions to improve healthcare and optimize medical processes.',
    financeDesc: 'Advanced technologies to secure transactions and optimize financial services.',
    retailDesc: 'E-commerce and analytics solutions to optimize customer experience and sales.',
    manufacturingDesc: 'IoT and analytics to improve productivity and reduce production costs.',
    
    // Industry solutions
    diseasePrediction: 'Disease prediction analysis',
    patientRecords: 'Patient records management',
    resourceOptimization: 'Resource optimization',
    fraudDetection: 'Fraud detection',
    riskAnalysis: 'Risk analysis',
    algorithmicTrading: 'Algorithmic trading',
    productRecommendation: 'Product recommendation',
    behavioralAnalysis: 'Behavioral analysis',
    inventoryOptimization: 'Inventory optimization',
    predictiveMaintenance: 'Predictive maintenance',
    supplyChainOptimization: 'Supply chain optimization',
    automatedQuality: 'Automated quality control',
    
    // Career
    careerTitle: 'Career',
    joinUs: 'Join Us',
    openPositions: 'Open Positions',
    careerJoinTagline: 'and be part of a team passionate about innovation',
    careerOpenPositionsDesc: 'Discover career opportunities at AfriBuilDigit Group',
    applyNow: 'Apply Now',
    benefitsTitle: 'Benefits',
    benefitsWhyJoin: 'Why join our team?',
    benefitFlexibleWork: 'Flexible work environment',
    benefitContinuousTraining: 'Continuous training',
    benefitInnovativeProjects: 'Innovative projects',
    benefitDynamicTeam: 'Dynamic team',
    benefitCareerGrowth: 'Career growth',
    benefitCompetitiveSalary: 'Competitive salary',
    careerNoIdealPosition: "Can't find the ideal role?",
    careerSendCVPrompt: 'Send us your resume and we will contact you for future opportunities',
    careerSendCVButton: 'Send your resume',
    positionDataScientistTitle: 'Senior Data Scientist',
    positionDataScientistDept: 'Data Science',
    positionDataScientistLocation: 'Yaoundé, Cameroon',
    positionDataScientistType: 'Full-time',
    positionDataScientistDesc: 'We are seeking an experienced Data Scientist to join our team.',
    positionFullStackTitle: 'Full-Stack Developer',
    positionFullStackDept: 'Development',
    positionFullStackLocation: 'Yaoundé, Cameroon',
    positionFullStackType: 'Full-time',
    positionFullStackDesc: 'Passionate developer to build modern web applications.',
    positionDataEngineerTitle: 'Data Engineer',
    positionDataEngineerDept: 'Data Engineering',
    positionDataEngineerLocation: 'Yaoundé, Cameroon',
    positionDataEngineerType: 'Full-time',
    positionDataEngineerDesc: 'Expert in data architectures and ETL pipelines.',
    
    // Languages
    language: 'Language'
  },
  ////////////////////////////////////////////////////////////////////////////
  /////                          ########### langue allemand ###########
    de: {
    // Navigation
    home: 'Startseite',
    about: 'Über uns',
    industries: 'Branchen',
    services: 'Dienstleistungen',
    career: 'Karriere',
    contact: 'Kontakt',
    
    // Home page
    heroTitle: 'AfriBuilDigit Group',
    heroSubtitle1: 'Eine anregende Vision.',
    heroSubtitle2: 'Eine Wertschöpfung.',
    heroSubtitle: 'Ihr vertrauensvoller Partner für IT-Dienstleistungen',
    heroDescription: 'Junges und dynamisches Unternehmen, spezialisiert auf Datenwissenschaft, Datenengineering, Datenanalyse und Softwareentwicklung.',
    getStarted: 'Loslegen',
    learnMore: 'Mehr erfahren',
    ourServices: 'Unsere Dienstleistungen',
    discoverServices: 'Entdecken Sie unsere vollständige Palette spezialisierter IT-Dienstleistungen',
    learnMoreLink: 'Mehr erfahren',
    whyChooseUs: 'Warum uns wählen?',
    whatMakesUsDifferent: 'Entdecken Sie, was uns von der Konkurrenz unterscheidet',
    readyToTransform: 'Bereit, Ihre Branche zu transformieren?',
    contactToday: 'Sie haben noch weitere Fragen, benötigen Informationen oder wünschen einen Rückruf? Hinterlassen Sie uns Ihre Nachricht - wir sind gerne für Sie da.',
    discoverOurServices: 'Unsere Dienstleistungen entdecken',
    technologiesTools: 'Technologien & Tools',
    modernTechnologies: 'Wir verwenden die modernsten Technologien für Ihre Projekte',
    dataScienceML: 'Datenwissenschaft & ML',
    dataEngineering: 'Datenengineering',
    development: 'Entwicklung',
    
    // Features of the home page
    experiencedTeam: 'Erfolgreiche Team',
    experiencedTeamDesc: 'Unsere Gründer haben viele Jahre Erfahrung bei der Implementierung von auf Daten basierenden Lösungen gesammelt.',
    customSolutions: 'Angepasste Lösungen',
    customSolutionsDesc: 'Wir bringen technische Expertise und eine tiefgreifende Verständnis von Geschäftsprozessen.',
    technicalExcellence: 'Technische Exzellenz',
    technicalExcellenceDesc: 'Wir halten die höchsten Qualitätsstandards in all unseren Projekten.',
    continuousInnovation: 'Fortlaufende Innovation',
    continuousInnovationDesc: 'Wir bleiben auf dem neuesten Stand der neuesten Technologien und Methoden.',
    
    // Statistics
    projectsCompleted: 'Projekte abgeschlossen',
    satisfiedClients: 'Zufriedene Kunden',
    yearsExperience: 'Jahre Erfahrung',
    successRate: 'Erfolgsquote',
    
    // Services
    softwareDevelopment: 'Software Engineering',
    digitale: 'Digitalisierung',
    consulting: 'AI Consulting und Implementierung',
    cloudsolutions: 'Cloud Solutions & Services',
    dataAnalytics: 'Data und Analytics',
    security: 'Cybersecurity',
    servicesTitle: 'Unsere Dienstleistungen',
    servicesSubtitle: 'Mit breitem Fachwissen, Tools und Methoden entwickeln wir fortschrittliche und sichere Lösungen, kontinuierlich und effizient. Wir begleiten ihre Zukunftsgestaltung. Von der Idee bis zur Umsetzung. Entdecken Sie unsere vollständige Palette spezialisierter IT-Dienstleistungen',
    whatWeOffer: 'Was wir anbieten:',
    readyToStart: 'Bereit, Ihr Projekt zu starten?',
    contactForQuote: 'Kontaktieren Sie uns, um Ihre Bedürfnisse zu besprechen und ein personalisiertes Angebot zu erhalten',
    
    // Neue Dienstleistungen
    softwareEngineering: 'Software-Engineering',
    dataAnalyticsServices: 'Datenanalyse',
    aiMlDataScience: 'KI, ML und Datenwissenschaft',
    cloudDataEngineering: 'Cloud-Datenengineering',
    cloudServices: 'Cloud',
    cybersecurity: 'Cybersicherheit',
    embeddedSoftwareIoT: 'Eingebettete Software und IoT',
    intelligentPlatformsRPA: 'Intelligente Plattformen und RPA',
    digitalTransformation: 'Digitale Transformation',
    
    // Beschreibungen der Dienstleistungen
    consultingDesc: 'KI-Lösungen für Ihr Unternehmen. Steigern Sie Effizienz und Wachstum mit AfriBuilDigit.',
    cloudsolutionsDesc: 'Beschleunigen Sie Ihre Cloud-Reise mit AfriBuilDigit. Erreichen Sie eine schnellere Wertschöpfungszeit.',
    dataAnalyticsDesc: 'Befreihen Sie das Potenzial Ihrer Daten mit AfriBuilDigit. KI-gestützte Erkenntnisse, modernisierte Plattformen und zukunftssichere Lösungen.',
    softwareDevelopmentDesc: 'Wir entwickeln robuste und innovative Anwendungen, die auf Ihre spezifischen Bedürfnisse zugeschnitten sind.',
    digitaleDesc: 'Nous développons des applications robustes et innovantes adaptées à vos besoins spécifiques.',
    securityDesc: 'Nous développons des applications robustes et innovantes adaptées à vos besoins spécifiques.',

    // Beschreibungen der neuen Dienstleistungen
    softwareEngineeringDesc: 'Ob Sie eine Idee validieren, eine maßgeschneiderte Lösung erstellen, Ihr System modernisieren, Ihre bestehenden Prozesse optimieren oder neue Technologien nutzen möchten - AfriBuilDigit ist für Sie da. Wir verbinden fundiertes Domänenwissen, Expertise in modernsten Technologien und besondere Aufmerksamkeit für Ihre Bedürfnisse, um Ihnen leistungsstarke technologische Lösungen und Dienstleistungen zu bieten. Neben Cloud-Lösungen, Datenanalyse, KI, IoT und UX-Design bieten wir eine breite Palette von Software-Engineering-Dienstleistungen.',
    dataAnalyticsServicesDesc: 'Optimieren Sie Ihre Abläufe, reduzieren Sie Risiken und transformieren Sie Ihre Daten in Einnahmen mit einem vertrauensvollen Partner an Ihrer Seite. Mit erfahrenen Daten-Ingenieuren und anerkannter Expertise in der Datenanalyse erfüllt AfriBuilDigit alle Ihre Geschäftsanforderungen, von der Gestaltung einer gewinnbringenden Strategie bis zur Implementierung einer effektiven Datenverwaltung, durch Big Data Engineering und die Erstellung komplexer Datenplattformen.',
    aiMlDataScienceDesc: 'Dank AfriBuilDigits Expertise in KI, Machine Learning und Datenwissenschaft können Sie alle Ihre Ziele erreichen: Automatisierung von Abläufen, Produktivitätssteigerung, datenbasierte Entscheidungsfindung und Gewinnsteigerung. Unsere Experten helfen Ihnen dabei, Erkenntnisse aus massiven Mengen strukturierter und unstrukturierter Daten zu extrahieren, Computer-Vision-Lösungen zu implementieren, Deep-Learning-Modelle zu erstellen und vieles mehr.',
    cloudDataEngineeringDesc: 'Die richtigen Daten zur richtigen Zeit und im richtigen Format zu haben, stellt einen Wettbewerbsvorteil für Unternehmen dar. Die Verwaltung der Datenkomplexität und -volumina kann jedoch für Unternehmen komplex sein: sammeln, verarbeiten und analysieren. Bei AfriBuilDigit helfen Ihnen unsere Cloud-Datenengineering-Dienstleistungen dabei, die ideale Dateninfrastruktur zu schaffen, um Ihre Geschäftsdaten zu sammeln, zu verarbeiten und einfach darauf zuzugreifen, um überall, jederzeit und auf jedem Gerät umsetzbare Erkenntnisse zu erhalten.',
    cloudServicesDesc: 'AfriBuilDigit zielt darauf ab, Organisationen dabei zu helfen, ihre Cloud-Reise zu gestalten, zu implementieren und kontinuierlich zu perfektionieren. Wir bieten eine umfassende Palette von Cloud-Entwicklungsdienstleistungen: von Cloud-Strategie und -Adoption bis DevOps, durch CI/CD-Optimierung und vieles mehr. Mit unseren Cloud-Ingenieuren und Dutzenden abgeschlossener Projekte können wir Ihrem Unternehmen helfen, viele langfristige Vorteile aus Ihren Cloud-Initiativen zu ziehen: Agilität, Kostenreduzierung, kürzere Time-to-Market, bessere Kundenerfahrung und vieles mehr.',
    cybersecurityDesc: 'Robuste Cybersicherheit ist keine einfache Option, sondern eine absolute Notwendigkeit. Die wachsende Komplexität und Häufigkeit von Cyber-Bedrohungen erfordert proaktive und umfassende Sicherheitsmaßnahmen zum Schutz der wertvollsten Vermögenswerte Ihres Unternehmens. AfriBuilDigit bietet Experten-Cybersicherheitsberatungsdienstleistungen, die darauf ausgelegt sind, Ihre Organisation vor potenziellen Bedrohungen zu schützen und die Integrität, Vertraulichkeit und Verfügbarkeit Ihrer Daten zu gewährleisten.',
    embeddedSoftwareIoTDesc: 'Als Full-Lifecycle-Partner für die Entwicklung eingebetteter Software und IoT begleitet AfriBuilDigit Sie in allen Aspekten Ihres IoT- oder eingebetteten Projekts, von der Validierung Ihrer Idee und der Erstellung eines Prototyps bis zur Gestaltung einer skalierbaren Cloud-Architektur und der optimalen Nutzung der prädiktiven Analyse. Unser einzigartiger Ansatz gewährleistet umfassende Unterstützung in jedem Schritt und optimiert den Entwicklungszyklus, wodurch Kosten und Zeitpläne optimiert werden.',
    intelligentPlatformsRPADesc: 'Mit über zwanzig Jahren Erfahrung in der Entwicklung maßgeschneiderter Software und über fünfzehn Jahren in der Unternehmensberatung bietet AfriBuilDigit fundierte Expertise in vielen digitalen Plattformen und RPA-Tools wie SAP, OpenText, Salesforce, Automation Anywhere, UIPath und anderen. Unsere zertifizierten Berater haben mit Dutzenden von Fortune-500-Unternehmen und führenden Unternehmen in den Bereichen Finanzen, Telekommunikation, Fertigung, Lieferkette, Vertrieb und anderen Sektoren zusammengearbeitet und ihnen dabei geholfen, den Wert ihrer Unternehmensanwendungen zu optimieren.',
    digitalTransformationDesc: 'Digitale Transformation ist ein bisschen wie eine Lawine auszulösen: Alles beginnt mit einer guten Idee, und sobald sie implementiert ist, verändert sich das gesamte Unternehmen radikal. Professionelle Beratung hilft Ihrem Team dabei, neue Wege zu finden, um effiziente Prozesse zu etablieren und digitale Geschäftsmodelle zu implementieren.',
    
    // Unterdienstleistungen
    softwareEngineeringServices: 'Software-Engineering-Dienstleistungen',
    customSolutionDevelopment: 'Maßgeschneiderte Lösungsentwicklung',
    applicationModernisation: 'Anwendungsmodernisierung',
    softwareQATesting: 'Software-QA & -Tests',
    technologyConsulting: 'Technologieberatung',
    softwareArchitectureConsulting: 'Software-Architekturberatung',
    techDueDiligence: 'Technische Due Diligence',
    digitalTransformationServices: 'Digitale Transformation',
    productDiscovery: 'Produktentdeckung',
    
    dataAnalyticsServicesList: 'Datenanalyse-Dienstleistungen',
    dataAnalyticsStrategy: 'Datenanalyse-Strategie',
    bigData: 'Big Data',
    dataGovernance: 'Datenverwaltung',
    dataWarehouseConsulting: 'Data Warehouse-Beratung',
    dataLakeConsulting: 'Data Lake-Beratung',
    businessIntelligence: 'Business Intelligence',
    
    aiMlDataScienceServices: 'KI, ML und Datenwissenschaft',
    dataScienceServices: 'Datenwissenschaft',
    artificialIntelligenceML: 'Entwicklung von künstlicher Intelligenz und maschinellem Lernen',
    mlOps: 'MLOps',
    generativeAIConsulting: 'Generative KI-Beratung',
    aiConsulting: 'KI-Beratung',
    computerVisionDevelopment: 'Computer-Vision-Entwicklung',
    
    cloudDataServices: 'Cloud-Datendienstleistungen',
    cloudMigration: 'Cloud-Migration',
    cloudArchitectureStrategies: 'Cloud-Architektur und -Strategien',
    devOpsAutomation: 'DevOps und Automatisierung',
    cloudInfrastructureManagement: 'Cloud-Infrastrukturmanagement',
    cloudDataIntegrationETL: 'Cloud-Datenintegration und ETL',
    
    cloudSolutions: 'Cloud-Lösungen',
    cloudNativeServices: 'Cloud-native Dienstleistungen',
    devOps: 'DevOps',
    awsConsulting: 'AWS-Beratung',
    awsMigration: 'AWS-Migration',
    awsOpenSearchService: 'AWS OpenSearch Service',
    awsWellArchitectedReview: 'AWS Well-Architected Review',
    cloudInfrastructureManagementServices: 'Cloud-Infrastrukturmanagement',
    azureConsulting: 'Azure-Beratung',
    gcpConsulting: 'GCP-Beratung',
    
    cybersecurityServices: 'Cybersicherheit',
    businessContinuity: 'Geschäftskontinuität',
    devSecOps: 'DevSecOps',
    penetrationTesting: 'Penetrationstests',
    strategyConsulting: 'Strategie und Beratung',
    applicationSecurity: 'Anwendungssicherheit',
    riskAssessment: 'Risikobewertung',
    compliance: 'Compliance',
    
    embeddedSoftwareDevelopment: 'Entwicklung eingebetteter Software',
    internetOfThingsDevelopment: 'Internet der Dinge-Entwicklung',
    firmwareDevelopmentServices: 'Firmware-Entwicklungsdienstleistungen',
    roboticsConsulting: 'Robotik-Beratung',
    
    sapConsulting: 'SAP-Beratung',
    sapOnAws: 'SAP auf AWS',
    openTextProfessionalServices: 'OpenText Professional Services',
    salesforce: 'Salesforce',
    intelligentAutomation: 'Intelligente Automatisierung',
    rpa: 'RPA',
    lowCodeNoCodeDevelopment: 'Low-Code/No-Code-Entwicklung',
    mendix: 'Mendix',
    pega: 'Pega',
    uiPath: 'UIPath',
    
    digitalisationStrategies: 'Digitalisierungsstrategien',
    changeManagement: 'Change Management',
    cloudService: 'Cloud-Service',
    financialTransformation: 'Finanzielle Transformation',
    digitalControl: 'Digitale Kontrolle',
    
    // Service features
    predictionModels: 'Erweiterte Vorhersagemodelle',
    sentimentAnalysis: 'Sentiment-Analyse',
    personalizedRecommendation: 'Personalisierte Empfehlungen',
    computerVision: 'Computer Vision',
    naturalLanguageProcessing: 'Verarbeitung natürlicher Sprache',
    processOptimization: 'Prozessoptimierung',
    cloudNativeArchitectures: 'Cloud-native Architekturen',
    dataPipelines: 'ETL/ELT Datenpipelines',
    dataLakes: 'Data Lakes und Data Warehouses',
    realTimeStreaming: 'Echtzeit-Datenstreaming',
    dataQualityManagement: 'Datenqualitätsmanagement',
    monitoringAlerting: 'Überwachung und Benachrichtigungen',
    interactiveDashboards: 'Interaktive Dashboards',
    automatedReports: 'Automatisierte Berichte',
    predictiveAnalysis: 'Prädiktive Analyse',
    customerSegmentation: 'Kundensegmentierung',
    businessKPIs: 'Business-KPIs und Metriken',
    dataVisualization: 'Datenvisualisierung',
    modernWebApps: 'Moderne Webanwendungen',
    restfulAPIs: 'RESTful und GraphQL APIs',
    mobileApps: 'Mobile Anwendungen',
    managementSystems: 'Management-Systeme',
    thirdPartyIntegrations: 'Drittanbieter-Integrationen',
    maintenanceSupport: 'Wartung und Support',
    
    // clients
    clientsTitle: 'Unsere Clients',
    clientsSubtitle: 'Die Anforderungen unserer Kunden an ihre IT, sind genauso vielfältig wie ihre Unternehmen und Branchen. Eines haben sie jedoch gemeinsam: Sie haben erkannt, dass moderne und zuverlässige IT-Umgebungen das Fundament für zukunftsfähige Geschäftsmodelle und wirtschaftlichen Erfolg sind.',
    
    // Solutions IT
    ourITSoftwareSolutions: 'Unsere IT und Software-Lösungen',
    advancedITForBusinessSuccess: 'Erweiterte IT für Ihren geschäftlichen Erfolg',
    solutionsFirstParagraph: 'Als hoch geprüfter Spezialist für IT-Dienstleistungen verfügen wir über ein umfangreiches Portfolio von Dienstleistungen: von den modernsten Cloud-Diensten bis hin zu angepassten IT-Infrastrukturen und verwalteten Dienstleistungen, einschließlich Sicherheits- und andere Support-Themen, alles ist inklusive für eine gut positionierte Unternehmens-IT, um die steigenden Anforderungen der Digitalisierung zu erfüllen.',
    solutionsSecondParagraph: 'Mit unseren intelligenten Software-Lösungen beherrschen wir individuelle Herausforderungen und optimieren komplexe Geschäftsprozesse in enger Zusammenarbeit mit unseren Kunden. Wir erfüllen präzise die spezifischen Anforderungen unserer Kunden-Branche und finden entweder die richtige Lösung in unserem erweiterten Software-Portfolio oder entwickeln die entsprechende angepasste Software für Ihr Unternehmen.',
    
    // About
    aboutTitle: 'Über uns',
    aboutDescription: 'Wir sind ein junges und dynamisches IT-Dienstleistungsunternehmen mit Sitz in Yaoundé, Kamerun.',
    experience: 'Erfahrung',
    expertise: 'Expertise',
    innovation: 'Innovation',
    ourHistory: 'Unsere Geschichte',
    historySubtitle: 'Entdecken Sie den Weg, der uns hier geführt hat',
    visionFromExperience: 'Eine Vision, die aus Erfahrung geboren wurde',
    visionDescription: 'AfriBuilDigit Group wurde aus der Vision gegründet, eine IT-Dienstleistungsgesellschaft zu schaffen, die technische Expertise und eine tiefgreifende Verständnis von Geschäftsprozessen vereint. Unsere Gründer, nachdem sie in großen internationalen Unternehmen gearbeitet hatten, entschieden, ihre Expertise für afrikanische Unternehmen zu nutzen.',
    basedInYaounde: 'Basierend in Yaoundé, Kamerun, hat sich unser Unternehmen schnell als zuverlässiger Partner für Unternehmen etabliert, die ihre Daten in wettbewerbsfähige Vorteile transformieren wollten.',
    foundingYear: 'Gründungsjahr',
    founders: 'Gründer',
    projectsCompleted: 'Projekte abgeschlossen',
    ourValues: 'Unsere Werte',
    valuesSubtitle: 'Die Prinzipien, die unsere täglichen Handlungen leiten',
    excellence: 'Exzellenz',
    excellenceDesc: 'Wir streben nach Exzellenz in allem, was wir tun, und halten die höchsten Qualitätsstandards bei all unseren Projekten bei.',
    passion: 'Begeisterung',
    passionDesc: 'Wir sind begeistert von Technologie und Innovation und übertragen diese Begeisterung auf unsere Kunden.',
    collaboration: 'Zusammenarbeit',
    collaborationDesc: 'Wir glauben an die Kraft der Zusammenarbeit und arbeiten eng mit unseren Kunden zusammen.',
    innovation: 'Innovation',
    innovationDesc: 'Wir bleiben auf dem neuesten Stand der neuesten Technologien, um innovative Lösungen anzubieten.',
    ourTeam: 'Unser Team',
    teamSubtitle: 'Treffen Sie die Experten, die AfriBuilDigit Group zu Ihrem zuverlässigen Partner machen',
    ceoFounder: 'CEO & Co-founder',
    ctoFounder: 'CTO & Co-founder',
    leadDataScientist: 'Lead Data Scientist',
    ctoDesc: 'Experte für Cloud Data Science und Datenengineering mit mehr als 10 Jahren professioneller Erfahrung',
    ceoDesc: 'Experte für Cloud Data Science und Software-Ingenieur, spezialisiert auf Cloud-Architekturen.',
    dataScientistDesc: 'Spezialist für maschinelles Lernen und künstliche Intelligenz.',
    ourMission: 'Unsere Mission',
    missionDescription: 'Wir helfen unseren Kunden, fundierte Entscheidungen auf der Grundlage von Daten zu treffen und effektiv digitale Lösungen zu implementieren. Ob es sich um moderne Datenarchitekten, maschinelle Lernanwendungen oder robuste Backend-Entwicklung handelt, wir sind Ihr zuverlässiger Partner.',
    africanContext: 'Lösungen angepasst an den afrikanischen Kontext',
    technicalExcellence: 'Anerkannter technischer Fortschritt',
    measurableResults: 'Messbare und dauerhafte Ergebnisse',
    
    // Footer
    followUs: 'Folgen Sie uns',
    allRightsReserved: 'Alle Rechte vorbehalten',
    
    // Contact
    contactUs: 'Kontaktieren Sie uns',
    name: 'Name',
    email: 'E-Mail',
    message: 'Nachricht',
    send: 'Senden',
    contactInfo: 'Kontaktinformationen',
    contactInfoDesc: 'Bitte kontaktieren Sie uns für Fragen. Wir freuen uns, Ihnen persönlich zu helfen und zu beraten. Wir nehmen uns die Zeit, Ihre Bedürfnisse zu hören und Ihnen, Ihnen und Ihrer Firma, angepasste Lösungen anzubieten, die Sie zum Erfolg führen. Bitte verwenden Sie unsere Formulare, um uns zu kontaktieren. Wir werden Ihnen in den kürzesten Zeiten antworten!',
    
    // Industries
    industriesTitle: 'Unsere Branchen',
    industriesSubtitle: 'Wir bedienen verschiedene Geschäftsbereiche mit maßgeschneiderten Lösungen',
    healthcare: 'Gesundheitswesen',
    finance: 'Finanzen',
    agritech:'Agritech',
    transport: 'Öffentliche Verkehrsmittel',
    retail: 'Einzelhandel & e-Commerce',
    manufacturing: 'Fertigung',
    readyToTransformIndustry: 'Bereit, Ihre Branche zu transformieren?',
    contactForIndustry: 'Kontaktieren Sie uns, um Ihre spezifischen Bedürfnisse zu besprechen und unsere an Ihre Branche angepassten Lösungen zu entdecken',
    
    // Industry descriptions
    healthcareDesc: 'Innovative Lösungen zur Verbesserung der Gesundheitsversorgung und Optimierung medizinischer Prozesse.',
    financeDesc: 'Fortschrittliche Technologien zur Sicherung von Transaktionen und Optimierung von Finanzdienstleistungen.',
    retailDesc: 'E-Commerce und Analytics-Lösungen zur Optimierung der Kundenbetreuung und des Verkaufs.',
    manufacturingDesc: 'IoT und Analytics zur Verbesserung der Produktivität und Reduzierung der Produktionskosten.',
    
    // Industry solutions
    diseasePrediction: 'Krankheitsvorhersage-Analyse',
    patientRecords: 'Patientenaktenverwaltung',
    resourceOptimization: 'Ressourcenoptimierung',
    fraudDetection: 'Betrugserkennung',
    riskAnalysis: 'Risikoanalyse',
    algorithmicTrading: 'Algorithmischer Handel',
    productRecommendation: 'Produktempfehlungen',
    behavioralAnalysis: 'Verhaltensanalyse',
    inventoryOptimization: 'Lageroptimierung',
    predictiveMaintenance: 'Prädiktive Wartung',
    supplyChainOptimization: 'Lieferkettenoptimierung',
    automatedQuality: 'Automatisierte Qualitätskontrolle',
    
    // Career
    careerTitle: 'Karriere',
    joinUs: 'Werden Sie Teil unseres Teams',
    openPositions: 'Offene Stellen',
    careerJoinTagline: 'und werden Sie Teil eines Teams, das für Innovation brennt',
    careerOpenPositionsDesc: 'Entdecken Sie Karrieremöglichkeiten bei AfriBuilDigit Group',
    applyNow: 'Bewerben',
    benefitsTitle: 'Vorteile',
    benefitsWhyJoin: 'Warum unserem Team beitreten?',
    benefitFlexibleWork: 'Flexibles Arbeitsumfeld',
    benefitContinuousTraining: 'Kontinuierliche Weiterbildung',
    benefitInnovativeProjects: 'Innovative Projekte',
    benefitDynamicTeam: 'Dynamisches Team',
    benefitCareerGrowth: 'Karrierewachstum',
    benefitCompetitiveSalary: 'Wettbewerbsfähiges Gehalt',
    careerNoIdealPosition: 'Nicht die ideale Stelle gefunden?',
    careerSendCVPrompt: 'Senden Sie uns Ihren Lebenslauf und wir kontaktieren Sie für zukünftige Möglichkeiten',
    careerSendCVButton: 'Lebenslauf senden',
    positionDataScientistTitle: 'Senior Data Scientist',
    positionDataScientistDept: 'Data Science',
    positionDataScientistLocation: 'Yaoundé, Kamerun',
    positionDataScientistType: 'Vollzeit',
    positionDataScientistDesc: 'Wir suchen eine erfahrene Data Scientist zur Verstärkung unseres Teams.',
    positionFullStackTitle: 'Full-Stack-Entwickler',
    positionFullStackDept: 'Entwicklung',
    positionFullStackLocation: 'Yaoundé, Kamerun',
    positionFullStackType: 'Vollzeit',
    positionFullStackDesc: 'Leidenschaftlicher Entwickler für moderne Webanwendungen.',
    positionDataEngineerTitle: 'Data Engineer',
    positionDataEngineerDept: 'Data Engineering',
    positionDataEngineerLocation: 'Yaoundé, Kamerun',
    positionDataEngineerType: 'Vollzeit',
    positionDataEngineerDesc: 'Experte für Datenarchitekturen und ETL-Pipelines.',
    
    // Languages
    language: 'Sprache'
  }
}

const LanguageContext = createContext()

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('fr')
  
  const t = (key) => {
    return translations[currentLanguage][key] || key
  }
  
  const changeLanguage = (language) => {
    setCurrentLanguage(language)
  }
  
  const value = {
    currentLanguage,
    changeLanguage,
    t
  }
  
  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
} 